name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: Testes Unitários e de Integração ---
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test -Punit-tests

      - name: Run Integration Tests

        run: mvn verify -Pintegration-tests -Dsurefire.skip=true

  # --- JOB 2: Testes E2E ---
  e2e-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run e2e Tests
        # Ignora os unitários também aqui!
        run: mvn verify -Pe2e-tests -Dsurefire.skip=true